import memjs

export {
    memcachedSerializeUser: serializeUser
    memcachedDeserializeUser: deserializeUser
}

cache = memjs.Client.create()

serializeUser = (user, done) ->
    cache.set(user.username, JSON.stringify(user), (err, success) ->
        done(null, user.username)
    )

deserializeUser = (username, done) ->
    cache.get(username, (err, value, key) ->
        user = JSON.parse(value)
        done(null, user)
    )
